# This is a basic workflow to help you get started with Actions

name: dev-full

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: []
    paths:
    - .github/workflows/windows-dev-full.yml
    
  pull_request:
    branches: []
    paths:
    - .github/workflows/windows-dev-full.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows-dev-full:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: ls /dev
        run: |
          ls -l /dev || echo ignore errors.
        shell: bash
        
      - name: echo to dev/full
        run: |
          echo test > /dev/full || echo "did you see?"
        shell: bash
